# UDP config
UDP_HOST = ""
UDP_PORT = 60005
UDP_BROADCAST_HOST = '<broadcast>'
UDP_RESPONSE_TIMEOUT = 0.2

# predefined message flags
CONFIG_UPDATE = 0x00
PLAYER_START = 0x01
PLAYER_STOP = 0x02
SERVER_REQUEST = 0x03
FILELIST_REQUEST = 0x04
FILELIST_RESPONSE = 0x05
CONFIG_REQUEST = 0x06

# msg interpreter result
INTERPRETER_SUCCESS = 0xf00
INTERPRETER_SERVER_REQUEST = 0xf01
INTERPRETER_ERROR = 0xf02
INTERPRETER_FILELIST_REQUEST = 0xf03
INTERPRETER_FILELIST_RESPONSE = 0xf04

# player states
PLAYER_STARTED = 0x80
PLAYER_STOPPED = 0x81
PLAYER_STATE_UNDEFINED = 0x82

# response observer types
OBS_HOST_SEARCH = 0xe0
OBS_FILE_LIST = 0xe1
OBS_CONFIG = 0xe2
OBS_STOP = 0xee
